name: vanita_lunch_app
description: A Flutter app for Vanita Lunch Home staff to take orders.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^26.1.35
  provider: ^6.1.2
  printing: ^5.12.0
  pdf: ^3.10.7

  # --- Printing Dependencies ---
  blue_thermal_printer: ^1.2.3
  #---esc_pos_utils: ^1.1.0
  esc_pos_utils_plus: ^2.0.3
  intl: ^0.18.1

  # --- ADD THIS PACKAGE ---
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/vanita.lunch.home/
